services:
  - type: web
    name: sample-service-name
    region: ohio
    env: python
    plan: free

    runtime: python-3.11.9
    

    buildCommand: "./render_build.sh"
    startCommand: "gunicorn backend.app:app"

    envVars:
      - key: BASENAME
        value: /

      - key: FLASK_APP
        value: src/app.py

      - key: FLASK_DEBUG
        value: "0"

      - key: FLASK_APP_KEY
        value: "any key works"
